services:
  - type: web
    name: doc-squeeze-api
    env: docker
    branch: master
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /
    port: 3000
